version: '3.8'

services:
  # --- Сервис Базы данных (PostgreSQL) ---
  db:
    image: postgres:14-alpine
    container_name: student_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Сервис Приложения (Django + Gunicorn) ---
  app:
    build: .
    container_name: student_app_container
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    command: sh /app/entrypoint.sh
    depends_on:
      db:
        condition: service_healthy

  # --- Сервис Веб-сервера (Nginx) ---
  nginx:
    build: ./nginx
    container_name: student_nginx_container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:

#docker-compose exec app python manage.py createsuperuser