version: '3.8'

services:
  app:
    # Имя контейнера, который будет создан
    container_name: student_app_container

    # Инструкция по сборке образа
    # 'build: .' означает "собрать образ из Dockerfile в текущей директории"
    build: .

    # Перезапускать контейнер, если он упал (кроме случая, когда он был остановлен вручную)
    restart: unless-stopped

    # Проброс портов: [порт на хост-машине]:[порт внутри контейнера]
    # Ваше приложение будет доступно на 8080 порту виртуальной машины
    ports:
      - "8080:80"

    # Переменные окружения, которые будут доступны внутри контейнера
    # Django (в settings.py) будет их читать
    environment:
      # --- Секреты Django ---
      - SECRET_KEY=201175633203Knok
      - DEBUG=False
      - ALLOWED_HOSTS='*'

      # --- Настройки для подключения к ВНЕШНЕЙ базе данных ---
      - POSTGRES_DB=uchet
      - POSTGRES_USER=dotologin
      - POSTGRES_PASSWORD=201175633203Knok
      - POSTGRES_HOST=192.168.1.198
      - POSTGRES_PORT=5432