# Generated by Django 5.2.6 on 2025-09-08 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('specialty', models.CharField(max_length=200, verbose_name='Название специальности')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('hours', models.IntegerField(verbose_name='Количество часов')),
                ('report_form', models.CharField(choices=[('экзамен', 'Экзамен'), ('зачет', 'Зачет')], max_length=20, verbose_name='Форма отчетности')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('admission_year', models.IntegerField(verbose_name='Год поступления')),
                ('form_of_study', models.CharField(choices=[('дневная', 'Дневная'), ('вечерняя', 'Вечерняя'), ('заочная', 'Заочная')], max_length=20, verbose_name='Форма обучения')),
                ('group_name', models.CharField(max_length=50, verbose_name='Номер/название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('grade', models.CharField(max_length=50, verbose_name='Оценка')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discipline', verbose_name='Дисциплина')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
            ],
        ),
    ]
